-- Migration: Create assessments table
-- Created at: 2026-06-03
-- Purpose: Stores clinical child malnutrition assessments, growth metrics, and AI risk predictions.

CREATE TABLE IF NOT EXISTS assessments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::TEXT, NOW()) NOT NULL,
  subject_id TEXT NOT NULL,
  age_months INT2 NOT NULL CHECK (age_months >= 0 AND age_months <= 59),
  gender TEXT NOT NULL,
  birth_weight NUMERIC NOT NULL,
  weight NUMERIC NOT NULL,
  height NUMERIC NOT NULL,
  recent_illness TEXT,
  chronic_illness TEXT,
  immunization_status TEXT,
  feeding_practice TEXT,
  household_income_level TEXT,
  parent_education_level TEXT,
  access_to_clean_water TEXT,
  sanitation_access TEXT,
  hiv_exposure TEXT,
  recurrent_diarrhea TEXT,
  exclusive_breastfeeding_6m TEXT,
  feeding_diversity_score INT2,
  ses_score INT2,
  z_score NUMERIC,
  whz_category TEXT,
  ml_risk TEXT,
  ml_confidence NUMERIC
);

-- Indexes for performance on common lookups
CREATE INDEX IF NOT EXISTS idx_assessments_subject_id ON assessments(subject_id);
CREATE INDEX IF NOT EXISTS idx_assessments_created_at ON assessments(created_at DESC);
